# Generated by Django 6.0.5 on 2026-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumise'), ('REVISION', 'Révision demandée'), ('ACCEPTED', 'Acceptée')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_type', models.CharField(choices=[('FIXED', 'Fixe'), ('HOURLY', 'Horaire')], default='FIXED', max_length=20)),
                ('category', models.CharField(choices=[('DEV_WEB', 'Développement Web'), ('DEV_MOBILE', 'Développement Mobile'), ('DESIGN', 'Design & Graphisme'), ('MARKETING', 'Marketing Digital'), ('REDACTION', 'Rédaction & Traduction'), ('VIDEO', 'Vidéo & Animation'), ('DATA', 'Data & IA'), ('AUTRE', 'Autre')], max_length=50)),
                ('skills_needed', models.JSONField(default=list)),
                ('level', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('DELIVERED', 'Livré'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('DISPUTED', 'En litige')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
