# Generated by Django 6.0.5 on 2026-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freelance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('MPESA', 'M-Pesa'), ('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack'), ('CARD', 'Carte bancaire')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ESCROWED', 'Fonds bloqués'), ('RELEASED', 'Libéré au freelance'), ('REFUNDED', 'Remboursé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
