# Generated by Django 6.0.5 on 2026-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_MESSAGE', 'Nouveau message'), ('NEW_PROPOSAL', 'Nouvelle offre'), ('PROPOSAL_ACCEPTED', 'Offre acceptée'), ('PROPOSAL_REJECTED', 'Offre refusée'), ('PAYMENT_RECEIVED', 'Paiement reçu'), ('PROJECT_DELIVERED', 'Projet livré'), ('REVISION_REQUESTED', 'Révision demandée'), ('PROJECT_COMPLETED', 'Projet terminé'), ('NEW_REVIEW', 'Nouvel avis')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
